include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.gr.dart
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
