targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/routes/**
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/router.dart
      riverpod_generator:
        options:
          provider_name_suffix: Pod
          provider_family_name_suffix: Pod
        generate_for:
          - lib/**/state/**_pod.dart
          - lib/routing/router.dart
