name: school_manager
description: An School Manager.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3 <4.0.0"

dependencies:
  auto_route: ^8.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  intl: ^0.18.1
  riverpod_annotation: ^2.3.4

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  meta: ^1.11.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
